/**
 * Render the intent-learner.mjs script.
 *
 * This generates a static Node.js ESM script (not project-specific) that:
 * 1. Reads .claude/hooks/intent-log.jsonl
 * 2. Groups entries by routed_to command
 * 3. For commands with 3+ entries: extracts common words, builds regex
 * 4. Appends new patterns to intent-router.mjs PATTERNS array
 * 5. Writes audit log to intent-promotions.jsonl
 * 6. Truncates processed entries from log
 */
export function renderIntentLearner(): string {
  return `#!/usr/bin/env node
/**
 * Kairn Intent Learner — Pattern Promotion (Tier 2 → Tier 1)
 * Runs on SessionStart to promote recurring Tier 2 patterns to Tier 1 regexes.
 * Generated by kairn describe.
 */

import { readFileSync, writeFileSync, appendFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';

const hooksDir = join(dirname(new URL(import.meta.url).pathname));
const logPath = join(hooksDir, 'intent-log.jsonl');
const routerPath = join(hooksDir, 'intent-router.mjs');
const promotionsPath = join(hooksDir, 'intent-promotions.jsonl');

// Read log entries
let entries = [];
try {
  const raw = readFileSync(logPath, 'utf-8').trim();
  if (!raw) {
    console.log(JSON.stringify({ "continue": true, suppressOutput: true }));
    process.exit(0);
  }
  entries = raw.split('\\n').map(line => {
    try { return JSON.parse(line); }
    catch { return null; }
  }).filter(Boolean);
} catch {
  // Log file doesn't exist or is unreadable — nothing to promote
  console.log(JSON.stringify({ "continue": true, suppressOutput: true }));
  process.exit(0);
}

if (entries.length === 0) {
  console.log(JSON.stringify({ "continue": true, suppressOutput: true }));
  process.exit(0);
}

// Group by routed_to command
const groups = {};
const remaining = [];
for (const entry of entries) {
  if (!entry.routed_to) { remaining.push(entry); continue; }
  if (!groups[entry.routed_to]) groups[entry.routed_to] = [];
  groups[entry.routed_to].push(entry);
}

// For each command with 3+ entries, extract common words and build regex
const promoted = [];
for (const [command, cmdEntries] of Object.entries(groups)) {
  if (cmdEntries.length < 3) {
    remaining.push(...cmdEntries);
    continue;
  }

  // Extract unique words from all prompts
  const wordFreq = {};
  for (const entry of cmdEntries) {
    const words = (entry.prompt || '').toLowerCase()
      .replace(/[^a-z\\s]/g, '')
      .split(/\\s+/)
      .filter(w => w.length > 2);
    const unique = [...new Set(words)];
    for (const word of unique) {
      wordFreq[word] = (wordFreq[word] || 0) + 1;
    }
  }

  // Find words that appear in at least half the entries
  const threshold = Math.ceil(cmdEntries.length / 2);
  const commonWords = Object.entries(wordFreq)
    .filter(([, count]) => count >= threshold)
    .map(([word]) => word)
    .filter(w => !['the', 'and', 'for', 'this', 'that', 'can', 'you', 'please'].includes(w));

  if (commonWords.length === 0) {
    remaining.push(...cmdEntries);
    continue;
  }

  // Build regex pattern from common words
  const patternStr = '\\\\b(' + commonWords.join('|') + ')\\\\b';

  // Read current router and check if pattern already exists
  try {
    const routerContent = readFileSync(routerPath, 'utf-8');
    if (commonWords.some(w => routerContent.includes(w + '|') || routerContent.includes('|' + w))) {
      remaining.push(...cmdEntries);
      continue;
    }

    // Append new pattern to PATTERNS array
    const newEntry = \`  { pattern: /\\\\b(\${commonWords.join('|')})/i,\\n    command: '\${command}',\\n    description: 'Learned from usage patterns' },\`;
    const insertPoint = routerContent.lastIndexOf('];');
    if (insertPoint === -1) {
      remaining.push(...cmdEntries);
      continue;
    }

    const updatedRouter = routerContent.slice(0, insertPoint) +
      newEntry + '\\n' +
      routerContent.slice(insertPoint);
    writeFileSync(routerPath, updatedRouter, 'utf-8');

    // Record promotion
    const promotion = {
      timestamp: new Date().toISOString(),
      command,
      pattern: patternStr,
      sourcePrompts: cmdEntries.map(e => e.prompt),
      commonWords,
    };
    promoted.push(promotion);
    appendFileSync(promotionsPath, JSON.stringify(promotion) + '\\n');

  } catch {
    remaining.push(...cmdEntries);
    continue;
  }
}

// Write back remaining (unprocessed) entries
writeFileSync(logPath, remaining.map(e => JSON.stringify(e)).join('\\n') + (remaining.length ? '\\n' : ''), 'utf-8');

console.log(JSON.stringify({ "continue": true, suppressOutput: true }));
`;
}
