import type { IntentPattern } from './types.js';

/**
 * Render a pattern entry as a JavaScript object literal for embedding
 * in the generated intent-router.mjs script.
 */
function renderPatternEntry(p: IntentPattern): string {
  // Escape backslashes for embedding in a JS regex literal
  const escapedPattern = p.pattern.replace(/\\/g, '\\\\');
  const escapedDesc = p.description.replace(/'/g, "\\'");
  const escapedCmd = p.command.replace(/'/g, "\\'");
  return `  { pattern: /${p.pattern}/i,\n    command: '${escapedCmd}',\n    description: '${escapedDesc}' }`;
}

/**
 * Render the full intent-router.mjs script.
 *
 * This generates a Node.js ESM script that:
 * 1. Reads the user prompt from stdin (Claude Code hooks API)
 * 2. Sanitizes it (strips code blocks, URLs, file paths)
 * 3. Filters out informational questions
 * 4. Matches against project-specific regex patterns
 * 5. Returns additionalContext on match, or falls through to Tier 2
 */
export function renderIntentRouter(
  patterns: IntentPattern[],
  generationTimestamp: string,
): string {
  const patternEntries = patterns
    .map(p => renderPatternEntry(p))
    .join(',\n');

  return `#!/usr/bin/env node
/**
 * Kairn Intent Router — Tier 1 (Regex)
 * Generated by kairn describe. Project-specific keyword patterns.
 *
 * If a keyword matches, injects a system-reminder pointing Claude
 * to the right command/workflow. If no match, falls through to
 * the Tier 2 prompt hook.
 *
 * Last updated: ${generationTimestamp}
 */

import { readFileSync } from 'fs';

// Read prompt from stdin (Claude Code hooks API)
const input = readFileSync('/dev/stdin', 'utf-8');
let prompt = '';
try {
  const data = JSON.parse(input);
  prompt = data.prompt || '';
} catch { process.exit(0); }

if (!prompt.trim()) {
  console.log(JSON.stringify({ "continue": true, suppressOutput: true }));
  process.exit(0);
}

// Sanitize: strip code blocks, URLs, file paths
const clean = prompt
  .replace(/\`\`\`[\\s\\S]*?\`\`\`/g, '')
  .replace(/\`[^\`]+\`/g, '')
  .replace(/https?:\\/\\/\\S+/g, '')
  .replace(/(\\/[\\w.-]+){2,}/g, '')
  .toLowerCase();

// Question filter: don't trigger on informational queries
const QUESTION_PATTERNS = [
  /\\b(?:what(?:'s|\\s+is)|how\\s+(?:to|do\\s+i)\\s+use|explain|describe|tell\\s+me\\s+about)\\b/i,
];
function isQuestion(text, position, length) {
  const start = Math.max(0, position - 80);
  const end = Math.min(text.length, position + length + 80);
  const ctx = text.slice(start, end);
  return QUESTION_PATTERNS.some(p => p.test(ctx));
}

// ═══════════════════════════════════════════════
// PROJECT-SPECIFIC KEYWORD PATTERNS
// Generated from: kairn describe analysis
// Last updated: ${generationTimestamp}
// ═══════════════════════════════════════════════

const PATTERNS = [
${patternEntries}
];

// Match against patterns
for (const { pattern, command, description } of PATTERNS) {
  const match = clean.match(pattern);
  if (match && !isQuestion(clean, match.index, match[0].length)) {
    const output = {
      "continue": true,
      hookSpecificOutput: {
        hookEventName: 'UserPromptSubmit',
        additionalContext: \`[INTENT ROUTED] Based on your request, use: \${command} — \${description}\\n\\nUser's original request: \${prompt}\\n\\nExecute the command above to fulfill the user's intent.\`
      }
    };
    console.log(JSON.stringify(output));
    process.exit(0);
  }
}

// No match — fall through to Tier 2 (prompt hook)
console.log(JSON.stringify({ "continue": true, suppressOutput: true }));
`;
}
