import fs from 'fs/promises';
import path from 'path';
import { stringify as yamlStringify } from 'yaml';
import { loadConfig } from '../config.js';
import { selectTemplatesForWorkflow, generateTasksFromTemplates } from './templates.js';
import type { EvolveConfig, Task, ProjectProfileSummary } from './types.js';

/**
 * Creates the .kairn-evolve/ directory structure and writes config.yaml.
 * Returns the path to the workspace.
 */
export async function createEvolveWorkspace(
  projectRoot: string,
  config: EvolveConfig,
): Promise<string> {
  const workspace = path.join(projectRoot, '.kairn-evolve');

  // Create directories
  await fs.mkdir(path.join(workspace, 'baseline'), { recursive: true });
  await fs.mkdir(path.join(workspace, 'traces'), { recursive: true });
  await fs.mkdir(path.join(workspace, 'iterations'), { recursive: true });

  // Write config.yaml using proper YAML serialization
  const configObj = {
    model: config.model,
    proposer_model: config.proposerModel,
    scorer: config.scorer,
    max_iterations: config.maxIterations,
    parallel_tasks: config.parallelTasks,
  };
  await fs.writeFile(
    path.join(workspace, 'config.yaml'),
    yamlStringify(configObj),
    'utf-8',
  );

  return workspace;
}

/**
 * Writes tasks.yaml to the workspace using proper YAML serialization.
 *
 * Each task is serialized with all required fields. The rubric key
 * is only included when the task has rubric criteria defined.
 */
export async function writeTasksFile(
  workspacePath: string,
  tasks: Task[],
): Promise<void> {
  const doc = {
    tasks: tasks.map((t) => ({
      id: t.id,
      template: t.template,
      description: t.description,
      setup: t.setup,
      expected_outcome: t.expected_outcome,
      scoring: t.scoring,
      ...(t.rubric ? { rubric: t.rubric } : {}),
      timeout: t.timeout,
      ...(t.category ? { category: t.category } : {}),
    })),
  };

  const header =
    '# .kairn-evolve/tasks.yaml\n# Auto-generated by kairn evolve init — edit freely\n';
  await fs.writeFile(
    path.join(workspacePath, 'tasks.yaml'),
    header + yamlStringify(doc),
    'utf-8',
  );
}

/**
 * Build a lightweight project profile by scanning key files in the project root.
 *
 * Reads package.json for Node.js projects, checks for pyproject.toml or
 * requirements.txt for Python projects, and scans for common configuration files.
 */
export async function buildProjectProfile(
  projectRoot: string,
): Promise<ProjectProfileSummary> {
  const profile: ProjectProfileSummary = {
    language: null,
    framework: null,
    scripts: {},
    keyFiles: [],
  };

  // Try to read package.json for Node.js projects
  try {
    const pkgStr = await fs.readFile(
      path.join(projectRoot, 'package.json'),
      'utf-8',
    );
    const pkg = JSON.parse(pkgStr) as Record<string, unknown>;
    profile.language = 'typescript';

    if (pkg.scripts && typeof pkg.scripts === 'object') {
      profile.scripts = pkg.scripts as Record<string, string>;
    }

    // Detect framework from dependencies
    const deps: Record<string, string> = {
      ...((pkg.dependencies as Record<string, string>) ?? {}),
      ...((pkg.devDependencies as Record<string, string>) ?? {}),
    };

    if (deps.next) {
      profile.framework = 'Next.js';
    } else if (deps.express) {
      profile.framework = 'Express';
    } else if (deps.react) {
      profile.framework = 'React';
    } else if (deps.vue) {
      profile.framework = 'Vue';
    } else if (deps.commander) {
      profile.framework = 'CLI (Commander.js)';
    }
  } catch {
    // Not a Node.js project
  }

  // Try pyproject.toml / requirements.txt for Python
  if (!profile.language) {
    try {
      await fs.access(path.join(projectRoot, 'pyproject.toml'));
      profile.language = 'python';
    } catch {
      try {
        await fs.access(path.join(projectRoot, 'requirements.txt'));
        profile.language = 'python';
      } catch {
        // Not Python either
      }
    }
  }

  // Scan for key files
  try {
    const entries = await fs.readdir(projectRoot);
    const keyPatterns = [
      'README.md',
      'package.json',
      'tsconfig.json',
      'pyproject.toml',
      'Cargo.toml',
      'go.mod',
      'Makefile',
      'Dockerfile',
    ];
    profile.keyFiles = entries.filter((e) => keyPatterns.includes(e));
  } catch {
    // Ignore
  }

  return profile;
}

/**
 * Auto-generate project-specific eval tasks using the LLM.
 *
 * Reads the project's CLAUDE.md (if present), builds a project profile
 * by scanning key files, selects eval templates for the given workflow
 * type, then calls the LLM to generate concrete tasks.
 *
 * @param projectRoot - Path to the project root directory
 * @param workflowType - The type of workflow (e.g., "feature-development", "maintenance")
 * @returns Array of generated Task objects
 */
export async function autoGenerateTasks(
  projectRoot: string,
  workflowType: string,
): Promise<Task[]> {
  const config = await loadConfig();
  if (!config) {
    throw new Error('No config found. Run `kairn init` first.');
  }

  // Read CLAUDE.md
  let claudeMd = '';
  try {
    claudeMd = await fs.readFile(
      path.join(projectRoot, '.claude', 'CLAUDE.md'),
      'utf-8',
    );
  } catch {
    // CLAUDE.md is optional but recommended
  }

  // Build project profile by scanning key files
  const profile = await buildProjectProfile(projectRoot);

  // Select templates for workflow type
  const templates = selectTemplatesForWorkflow(workflowType);

  // Generate tasks via LLM
  return generateTasksFromTemplates(claudeMd, profile, templates, config);
}
