import type { EnvironmentSpec, AutonomyLevel } from "./types.js";

const AUTONOMY_LABELS: Record<AutonomyLevel, string> = {
  1: "Guided",
  2: "Assisted",
  3: "Autonomous",
  4: "Full Auto",
};

/** Welcome hook — shows orientation on first session */
const WELCOME_HOOK = {
  matcher: "",
  hooks: [{
    type: "command" as const,
    command: "if [ ! -f .claude/.toured ]; then echo '\\n  Welcome to your Kairn environment!\\n  Type /project:tour for a walkthrough, or /project:help for a quick reference.\\n'; fi",
  }],
};

// ── Level 1: Guided ─────────────────────────────────────────────

const TOUR_COMMAND = `# Environment Tour

Welcome! Let me show you around this Kairn environment.

## Your Commands
Read .claude/commands/ and list each one with a one-line description.
Group them by workflow phase:

  PLAN:    /project:spec, /project:sprint, /project:plan
  BUILD:   (just start coding — Claude reads CLAUDE.md automatically)
  VERIFY:  /project:prove, /project:grill, /project:test
  SHIP:    /project:commit, /project:review
  MANAGE:  /project:status, /project:tasks, /project:reset

## Your Agents
Read .claude/agents/ and explain each one with how to invoke it.

## Your MCP Tools
!claude mcp list 2>/dev/null || echo "Run /mcp in Claude Code to see active tools"

## Workflow
For this project, the recommended flow is:
  spec → sprint → plan → code → prove → grill → commit

## Tips
- Type / to see all commands
- Type @ to invoke an agent
- Paste raw errors — don't summarize them
- Use subagents for deep investigation
- Say "update CLAUDE.md" after any correction

After showing the tour, create .claude/.toured to suppress the welcome message:
!touch .claude/.toured

Ready to start? Try /project:spec to define your first feature.`;

function buildQuickstart(spec: EnvironmentSpec): string {
  const commands = Object.keys(spec.harness.commands || {});
  const agents = Object.keys(spec.harness.agents || {});

  const commandList = commands
    .map((c) => `- \`/project:${c}\``)
    .join("\n");

  const agentList = agents.length > 0
    ? agents.map((a) => `- \`@${a}\``).join("\n")
    : "- (none configured)";

  return `# Quick Start Guide

This environment was generated by Kairn. Here's how to use it.

## First Time
1. Open terminal in this directory
2. Run \`claude\`
3. Type \`/project:tour\` for a guided walkthrough

## Daily Workflow
1. \`/project:status\` — see where things stand
2. \`/project:spec\` — define what to build (Claude will interview you)
3. Start coding — Claude follows CLAUDE.md automatically
4. \`/project:prove\` — verify your work
5. \`/project:commit\` — ship it

## Commands
${commandList}

## Agents
${agentList}

## Need Help?
Type \`/project:help\` in Claude Code for a quick reference.
`;
}

// ── Level 2: Assisted ───────────────────────────────────────────

const LOOP_COMMAND_CODE = `# Development Loop

Run an assisted development cycle for the next feature.

## Phase 1: SPEC
Review docs/TODO.md and docs/SPRINT.md.
If no sprint is defined, run /project:spec to interview the user.
Wait for user approval of the spec.

## Phase 2: PLAN
Read the approved spec in docs/SPRINT.md.
Plan the implementation: files to change, tests to write, approach.
Write plan to docs/DECISIONS.md.
Wait for user approval of the plan.

## Phase 3: IMPLEMENT
Follow the plan. Implement the feature.
Run tests after each change.
Commit each logical unit: "feat: description"

## Phase 4: VERIFY
Run /project:prove to verify the implementation.
If confidence is LOW or MEDIUM, fix issues and re-verify.

## Phase 5: REVIEW
Run /project:grill for adversarial review.
Fix any BLOCKERs.

## Phase 6: SHIP
Run /project:commit.
Report what was built and what's next from docs/TODO.md.

Then ask: "Continue to next feature?"
If yes, return to Phase 1.`;

const LOOP_COMMAND_RESEARCH = `# Research Loop

Run an assisted research cycle.

## Phase 1: QUESTION
Review docs/TODO.md for the next research question.
If none, ask the user what to investigate.

## Phase 2: RESEARCH
Search, extract, and analyze sources.
Log findings to docs/SOURCES.md and docs/LEARNINGS.md.

## Phase 3: SYNTHESIZE
Review all findings. Write structured summary to docs/SUMMARY.md.
Cite all sources.

## Phase 4: REVIEW
Present the summary. Ask the user for feedback.
Revise based on feedback.

## Phase 5: NEXT
Update docs/TODO.md — mark question as done, identify follow-ups.
Ask: "Continue to next question?"`;

const PM_AGENT = `---
name: pm
description: Project manager agent. Maintains roadmap, specs features, prioritizes work.
model: opus
---

You are a project manager for this codebase.

Your responsibilities:
1. Maintain docs/TODO.md — keep it prioritized and current
2. Write specs to docs/SPRINT.md when asked
3. Review completed work and suggest what's next
4. Track decisions in docs/DECISIONS.md
5. Track learnings in docs/LEARNINGS.md

When invoked:
- Read all docs/ files to understand current state
- Read recent git log for what changed
- Suggest the highest-priority next task
- If asked to spec something, interview the user (5-8 questions)

You do NOT write code. You plan, spec, and prioritize.`;

// ── Level 3: Autonomous ─────────────────────────────────────────

const AUTO_COMMAND = `# Autonomous Development

PM-driven development loop with PR delivery.

## Phase 1: PLAN (@pm)
Use @pm to:
- Read docs/TODO.md and docs/SPRINT.md
- Select the highest-priority unfinished task
- Write a spec to docs/SPRINT.md
- Present the spec for approval

Wait for user approval. If approved, proceed.

## Phase 2: BRANCH
Create an isolated worktree:
  git worktree add ../project-feat-{name} -b feat/{name}
All implementation happens in the worktree.

## Phase 3: IMPLEMENT
In the worktree directory:
- Follow the spec in docs/SPRINT.md
- Build, test, commit after each change

## Phase 4: VERIFY
Run verification:
- Static analysis (linting, type checks)
- Run functional tests
- If NEEDS FIXES: fix and re-verify

## Phase 5: PR
Create a pull request:
  gh pr create --title "feat: {name}" --body "{spec + QA report}"

## Phase 6: NEXT
Report:
  "PR #{N} ready for review: {link}
   Next priority from TODO.md: {next task}
   Continue? (y/n)"

If yes, return to Phase 1 with next task.`;

// ── Level 4: Full Auto ──────────────────────────────────────────

const AUTOPILOT_COMMAND = `# Autopilot Mode

Continuous autonomous development. The PM plans, the loop executes,
PRs are opened automatically. You review when ready.

## Configuration
- Max features per session: 5 (prevent runaway)
- Stop on: test failure, build error, or blocked dependency
- All work in isolated worktrees
- Every feature = one PR

## The Loop
Repeat until max features reached or stopped:
1. @pm selects next priority from docs/TODO.md
2. Create worktree + branch
3. Implement the feature
4. Run verification (build, test, lint)
5. Open PR via gh
6. Report status
7. Move to next feature

## Stop Conditions
- Max 5 features per autopilot session
- Any BLOCKER from verification
- Build failure that can't be resolved in 3 attempts
- User presses Escape`;

const AUTOPILOT_WARNING = `
## Autopilot Mode Active
This environment is configured for autonomous operation.
The @pm agent plans features and /project:autopilot executes them.
All changes are delivered as PRs — review before merging.
Stop conditions: max 5 features, test failure, or Escape.`;

// ── Main export ─────────────────────────────────────────────────

function isResearchProject(spec: EnvironmentSpec): boolean {
  const commands = spec.harness.commands ?? {};
  return "research" in commands || "summarize" in commands;
}

/**
 * Apply autonomy-level-specific content to an EnvironmentSpec.
 * Mutates spec.harness by injecting commands, agents, hooks, and docs
 * appropriate for the selected autonomy level.
 */
export function applyAutonomyLevel(spec: EnvironmentSpec): void {
  const level = spec.autonomy_level ?? 1;
  const commands = spec.harness.commands ?? {};
  const agents = spec.harness.agents ?? {};
  const docs = spec.harness.docs ?? {};
  const settings = (spec.harness.settings ?? {}) as Record<string, unknown>;

  // Level 1+: Tour, QUICKSTART, welcome hook
  if (level >= 1) {
    if (!("tour" in commands)) {
      commands.tour = TOUR_COMMAND;
    }
    docs.QUICKSTART = buildQuickstart(spec);

    // Add SessionStart welcome hook
    const hooks = (settings.hooks ?? {}) as Record<string, unknown[]>;
    const sessionStart = (hooks.SessionStart ?? []) as unknown[];
    sessionStart.push(WELCOME_HOOK);
    hooks.SessionStart = sessionStart;
    settings.hooks = hooks;
  }

  // Level 2+: Loop, PM agent
  if (level >= 2) {
    if (!("loop" in commands)) {
      commands.loop = isResearchProject(spec)
        ? LOOP_COMMAND_RESEARCH
        : LOOP_COMMAND_CODE;
    }
    if (!("pm" in agents)) {
      agents.pm = PM_AGENT;
    }
  }

  // Level 3+: Auto command
  if (level >= 3) {
    if (!("auto" in commands)) {
      commands.auto = AUTO_COMMAND;
    }
  }

  // Level 4: Autopilot command + warning
  if (level >= 4) {
    if (!("autopilot" in commands)) {
      commands.autopilot = AUTOPILOT_COMMAND;
    }
    // Append warning to CLAUDE.md
    if (spec.harness.claude_md && !spec.harness.claude_md.includes("Autopilot Mode")) {
      spec.harness.claude_md += "\n" + AUTOPILOT_WARNING;
    }
  }

  // Write back
  spec.harness.commands = commands;
  spec.harness.agents = agents;
  spec.harness.docs = docs;
  spec.harness.settings = settings;
}

/** Human-readable label for an autonomy level. */
export function autonomyLabel(level: AutonomyLevel): string {
  return AUTONOMY_LABELS[level];
}
