import type { EnvironmentSpec, AutonomyLevel } from "./types.js";

const AUTONOMY_LABELS: Record<AutonomyLevel, string> = {
  1: "Guided",
  2: "Assisted",
  3: "Autonomous",
  4: "Full Auto",
};

/** Welcome hook — shows orientation on first session */
const WELCOME_HOOK = {
  matcher: "",
  hooks: [{
    type: "command" as const,
    command: "if [ ! -f .claude/.toured ]; then echo '\\n  Welcome to your Kairn environment!\\n  Type /project:tour for a walkthrough, or /project:help for a quick reference.\\n'; fi",
  }],
};

// ── Level 1: Guided ─────────────────────────────────────────────

const TOUR_COMMAND = `# Environment Tour

Welcome! Let me show you around this Kairn environment.

## Your Commands
Read .claude/commands/ and list each one with a one-line description.
Group them by workflow phase:

  PLAN:    /project:spec, /project:sprint, /project:plan
  BUILD:   /project:develop (full pipeline), or just start coding
  VERIFY:  /project:prove, /project:grill, /project:test
  SHIP:    /project:commit, /project:review
  MANAGE:  /project:status, /project:reset

## Your Agents
Read .claude/agents/ and explain each one with how to invoke it.

## Your MCP Tools
!claude mcp list 2>/dev/null || echo "Run /mcp in Claude Code to see active tools"

## Workflow
For this project, the recommended flow is:
  spec → sprint → plan → code → prove → grill → commit

## Tips
- Type / to see all commands
- Type @ to invoke an agent
- Paste raw errors — don't summarize them
- Use subagents for deep investigation
- Say "update CLAUDE.md" after any correction

After showing the tour, create .claude/.toured to suppress the welcome message:
!touch .claude/.toured

Ready to start? Try /project:spec to define your first feature.`;

function buildQuickstart(spec: EnvironmentSpec): string {
  const commands = Object.keys(spec.harness.commands || {});
  const agents = Object.keys(spec.harness.agents || {});

  const commandList = commands
    .map((c) => `- \`/project:${c}\``)
    .join("\n");

  const agentList = agents.length > 0
    ? agents.map((a) => `- \`@${a}\``).join("\n")
    : "- (none configured)";

  return `# Quick Start Guide

This environment was generated by Kairn. Here's how to use it.

## First Time
1. Open terminal in this directory
2. Run \`claude\`
3. Type \`/project:tour\` for a guided walkthrough

## Daily Workflow
1. \`/project:status\` — see where things stand
2. \`/project:spec\` — define what to build (Claude will interview you)
3. Start coding — Claude follows CLAUDE.md automatically
4. \`/project:prove\` — verify your work
5. \`/project:commit\` — ship it

## Commands
${commandList}

## Agents
${agentList}

## Need Help?
Type \`/project:help\` in Claude Code for a quick reference.
`;
}

// ── Bootstrap (Level 2+: command, Level 3+: SessionStart hook) ─

const BOOTSTRAP_COMMAND = `# Environment Snapshot

Run this command at the start of any session to gather runtime context.
This saves 2-5 exploratory turns.

1. Run the following compound command and read the output:
   \`\`\`bash
   echo '=== WORKING DIRECTORY ===' && pwd && \\
   echo '=== PROJECT FILES ===' && ls -la && \\
   echo '=== GIT STATUS ===' && (git status --short 2>/dev/null || echo 'not a git repo') && \\
   echo '=== LANGUAGES ===' && \\
   (node --version 2>&1 || true) && \\
   (python3 --version 2>&1 || true) && \\
   (go version 2>&1 || true) && \\
   (rustc --version 2>&1 || true) && \\
   echo '=== PACKAGE MANAGERS ===' && \\
   (npm --version 2>&1 && echo "npm $(npm --version 2>&1)" || true) && \\
   (pip3 --version 2>&1 || true) && \\
   (cargo --version 2>&1 || true) && \\
   echo '=== ENVIRONMENT ===' && \\
   (cat .env 2>/dev/null | sed 's/=.*/=***/' || echo 'no .env file')
   \`\`\`

2. Summarize the environment in 3-4 lines:
   - Runtime: [languages + versions found]
   - Project: [framework, key deps, file count]
   - State: [git branch, clean/dirty, .env present]

3. Keep this summary in context for the rest of the session.`;

function buildBootstrapHookCommand(spec: EnvironmentSpec): string {
  const checks: string[] = [
    "echo '--- Environment Snapshot ---'",
    "pwd",
    "ls -la --color=never | head -20",
    "echo '---'",
    "git status --short 2>/dev/null || true",
    "echo '---'",
  ];

  // Infer project type from claude_md content (Tech Stack section)
  const md = (spec.harness.claude_md ?? "").toLowerCase();
  if (md.includes("node") || md.includes("typescript") || md.includes("javascript") || md.includes("react") || md.includes("next")) {
    checks.push("node --version 2>&1 || true");
    checks.push("cat package.json 2>/dev/null | head -5 || true");
  }
  if (md.includes("python") || md.includes("django") || md.includes("flask") || md.includes("fastapi")) {
    checks.push("python3 --version 2>&1 || true");
  }
  if (md.includes("rust") || md.includes("cargo")) {
    checks.push("rustc --version 2>&1 || true");
  }
  if (md.includes("go ") || md.includes("golang")) {
    checks.push("go version 2>&1 || true");
  }

  // .env key masking — show KEY=***, never values
  checks.push("cat .env 2>/dev/null | sed 's/=.*/=***/' || true");

  return checks.join(" && ");
}

// ── Level 2: Assisted ───────────────────────────────────────────

const LOOP_COMMAND_CODE = `# Development Loop

Run an assisted development cycle for the next feature.

## Phase 1: SPEC
Review docs/SPRINT.md.
If no sprint is defined, run /project:spec to interview the user.
Wait for user approval of the spec.

## Phase 2: PLAN
Read the approved spec in docs/SPRINT.md.
Plan the implementation: files to change, tests to write, approach.
Write plan to docs/DECISIONS.md.
Wait for user approval of the plan.

## Phase 3: IMPLEMENT
Follow the plan. Implement the feature.
Run tests after each change.
Commit each logical unit: "feat: description"

## Phase 4: VERIFY
Run /project:prove to verify the implementation.
If confidence is LOW or MEDIUM, fix issues and re-verify.

## Phase 5: REVIEW
Run /project:grill for adversarial review.
Fix any BLOCKERs.

## Phase 6: COMPLETION GATE

Before shipping, run the Completion Verification checklist:

### Requirements Check
- [ ] Re-read the ORIGINAL task description (not your interpretation)
- [ ] Each explicit requirement is met with evidence (test output, diff)
- [ ] Each implicit requirement (error handling, types, tests) is addressed

### State Check
- [ ] Test suite passes
- [ ] Lint/typecheck passes
- [ ] \`git diff --stat\` — every changed file is intentional
- [ ] No debug artifacts (console.log, TODO, commented-out code, temp files)

### Perspective Check (1 sentence each)
- **Test engineer:** Most likely production failure mode?
- **Code reviewer:** What would I flag in review?
- **Requesting user:** Does this solve my actual problem?

ALL pass → proceed to ship. ANY fail → fix first, then re-verify.

## Phase 7: SHIP
Run /project:commit.
Report what was built and what's next from docs/SPRINT.md.

Then ask: "Continue to next feature?"
If yes, return to Phase 1.`;

const LOOP_COMMAND_RESEARCH = `# Research Loop

Run an assisted research cycle.

## Phase 1: QUESTION
Review docs/SPRINT.md for the next research question.
If none, ask the user what to investigate.

## Phase 2: RESEARCH
Search, extract, and analyze sources.
Log findings to docs/SOURCES.md and docs/LEARNINGS.md.

## Phase 3: SYNTHESIZE
Review all findings. Write structured summary to docs/SUMMARY.md.
Cite all sources.

## Phase 4: REVIEW
Present the summary. Ask the user for feedback.
Revise based on feedback.

## Phase 5: NEXT
Update docs/SPRINT.md — mark question as done, identify follow-ups.
Ask: "Continue to next question?"`;

const PM_AGENT = `---
name: pm
description: Project manager agent. Maintains roadmap, specs features, prioritizes work.
model: opus
---

You are a project manager for this codebase.

Your responsibilities:
1. Maintain docs/SPRINT.md — keep it prioritized and current
2. Write specs to docs/SPRINT.md when asked
3. Review completed work and suggest what's next
4. Track decisions in docs/DECISIONS.md
5. Track learnings in docs/LEARNINGS.md

When invoked:
- Read all docs/ files to understand current state
- Read recent git log for what changed
- Suggest the highest-priority next task
- If asked to spec something, interview the user (5-8 questions)

You do NOT write code. You plan, spec, and prioritize.`;

// ── Level 3: Autonomous ─────────────────────────────────────────

const AUTO_COMMAND = `# Autonomous Development

PM-driven development loop with PR delivery.

## Phase 1: PLAN (@pm)
Use @pm to:
- Read docs/SPRINT.md
- Select the highest-priority unfinished task
- Write a spec to docs/SPRINT.md
- Present the spec for approval

Wait for user approval. If approved, proceed.

## Phase 2: BRANCH
Create an isolated worktree:
  git worktree add ../project-feat-{name} -b feat/{name}
All implementation happens in the worktree.

## Phase 3: IMPLEMENT
In the worktree directory:
- Follow the spec in docs/SPRINT.md
- Build, test, commit after each change

## Phase 4: VERIFY
Run verification:
- Static analysis (linting, type checks)
- Run functional tests
- If NEEDS FIXES: fix and re-verify

## Phase 5: COMPLETION GATE

Before creating a PR, run the Completion Verification checklist:
- [ ] Re-read the ORIGINAL spec from docs/SPRINT.md
- [ ] Each requirement is met with evidence (test output, diff)
- [ ] Test suite + lint/typecheck pass
- [ ] \`git diff --stat\` — every changed file is intentional, no debug artifacts
- **Test engineer:** Most likely production failure mode?
- **Code reviewer:** What would I flag in review?
- **Requesting user:** Does this solve my actual problem?

ALL pass → proceed to PR. ANY fail → fix first, then re-verify.

Include the checklist results in the PR description.

## Phase 6: PR
Create a pull request:
  gh pr create --title "feat: {name}" --body "{spec + QA report + verification checklist}"

## Phase 7: NEXT
Report:
  "PR #{N} ready for review: {link}
   Next priority from SPRINT.md: {next task}
   Continue? (y/n)"

If yes, return to Phase 1 with next task.`;

// ── Level 4: Full Auto ──────────────────────────────────────────

const AUTOPILOT_COMMAND = `# Autopilot Mode

Continuous autonomous development. The PM plans, the loop executes,
PRs are opened automatically. You review when ready.

## Configuration
- Max features per session: 5 (prevent runaway)
- Stop on: test failure, build error, or blocked dependency
- All work in isolated worktrees
- Every feature = one PR

## The Loop
Repeat until max features reached or stopped:
1. @pm selects next priority from docs/SPRINT.md
2. Create worktree + branch
3. Implement the feature
4. Run verification (build, test, lint)
5. Run Completion Verification checklist:
   - Requirements met with evidence
   - Tests + lint/typecheck pass
   - No debug artifacts or unexpected file changes
   - 3-perspective check (test engineer, reviewer, user)
6. Open PR via gh (include verification results in PR body)
7. Report status
8. Move to next feature

## Stop Conditions
- Max 5 features per autopilot session
- Any BLOCKER from verification
- Completion Verification checklist fails after 2 fix attempts
- Build failure that can't be resolved in 3 attempts
- User presses Escape`;

const AUTOPILOT_WARNING = `
## Autopilot Mode Active
This environment is configured for autonomous operation.
The @pm agent plans features and /project:autopilot executes them.
All changes are delivered as PRs — review before merging.
Stop conditions: max 5 features, test failure, or Escape.`;

// ── Main export ─────────────────────────────────────────────────

function isResearchProject(spec: EnvironmentSpec): boolean {
  const commands = spec.harness.commands ?? {};
  return "research" in commands || "summarize" in commands;
}

/**
 * Apply autonomy-level-specific content to an EnvironmentSpec.
 * Mutates spec.harness by injecting commands, agents, hooks, and docs
 * appropriate for the selected autonomy level.
 */
export function applyAutonomyLevel(spec: EnvironmentSpec): void {
  const level = spec.autonomy_level ?? 1;
  const commands = spec.harness.commands ?? {};
  const agents = spec.harness.agents ?? {};
  const docs = spec.harness.docs ?? {};
  const settings = (spec.harness.settings ?? {}) as Record<string, unknown>;

  // All levels: persistence_routing setting
  if (!("persistence_routing" in settings)) {
    settings.persistence_routing = level >= 3 ? "auto" : "manual";
  }

  // Level 1+: Tour, QUICKSTART, welcome hook
  if (level >= 1) {
    if (!("tour" in commands)) {
      commands.tour = TOUR_COMMAND;
    }
    docs.QUICKSTART = buildQuickstart(spec);

    // Add SessionStart welcome hook
    const hooks = (settings.hooks ?? {}) as Record<string, unknown[]>;
    const sessionStart = (hooks.SessionStart ?? []) as unknown[];
    sessionStart.push(WELCOME_HOOK);
    hooks.SessionStart = sessionStart;
    settings.hooks = hooks;
  }

  // Level 2+: Bootstrap command, Loop, PM agent
  if (level >= 2) {
    if (!("bootstrap" in commands)) {
      commands.bootstrap = BOOTSTRAP_COMMAND;
    }
    if (!("loop" in commands)) {
      commands.loop = isResearchProject(spec)
        ? LOOP_COMMAND_RESEARCH
        : LOOP_COMMAND_CODE;
    }
    if (!("pm" in agents)) {
      agents.pm = PM_AGENT;
    }
  }

  // Level 3+: Auto command + SessionStart bootstrap hook
  if (level >= 3) {
    if (!("auto" in commands)) {
      commands.auto = AUTO_COMMAND;
    }

    // Add SessionStart bootstrap hook (automatic environment snapshot)
    const hooks = (settings.hooks ?? {}) as Record<string, unknown[]>;
    const sessionStart = (hooks.SessionStart ?? []) as unknown[];
    const bootstrapHook = {
      matcher: "",
      hooks: [{
        type: "command" as const,
        command: buildBootstrapHookCommand(spec),
      }],
    };
    sessionStart.push(bootstrapHook);
    hooks.SessionStart = sessionStart;
    settings.hooks = hooks;
  }

  // Level 4: Autopilot command + warning
  if (level >= 4) {
    if (!("autopilot" in commands)) {
      commands.autopilot = AUTOPILOT_COMMAND;
    }
    // Append warning to CLAUDE.md
    if (spec.harness.claude_md && !spec.harness.claude_md.includes("Autopilot Mode")) {
      spec.harness.claude_md += "\n" + AUTOPILOT_WARNING;
    }
  }

  // Write back
  spec.harness.commands = commands;
  spec.harness.agents = agents;
  spec.harness.docs = docs;
  spec.harness.settings = settings;
}

/** Human-readable label for an autonomy level. */
export function autonomyLabel(level: AutonomyLevel): string {
  return AUTONOMY_LABELS[level];
}
